fix(types): remove orphan rule violations from storage module
Remove duplicate trait implementations that violated Rust's orphan rules:
- Removed impl Display for BlockHash, TxHash, Address, TokenId
- Removed impl AsRef<[u8]> for BlockHash, TxHash, Address, TokenId
- Removed impl From<[u8; 32]> for BlockHash, TxHash, Address, TokenId

These traits are already implemented in lib-types where the types are defined.
The storage module now only provides extension traits (BlockHashExt, etc.)
with additional storage-specific methods.

Fixes PR #1660 compilation errors:
- error[E0117]: only traits defined in the current crate can be implemented
  for types defined outside of the crate